In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data_processed.csv')

In [3]:
df.head()

   Unnamed: 0                                         reviewText  overall
0           0  enjoy vintage books movies enjoyed reading boo...        1
1           1  book reissue old one author born 1910 era say ...        1
2           2  fairly interesting read old style terminology ...        1
3           3  never read amy brewster mysteries one really h...        1
4           4  like period pieces clothing lingo enjoy myster...        1

In [4]:
df.drop(columns='Unnamed: 0', inplace=True)

In [5]:
df.head()

                                          reviewText  overall
0  enjoy vintage books movies enjoyed reading boo...        1
1  book reissue old one author born 1910 era say ...        1
2  fairly interesting read old style terminology ...        1
3  never read amy brewster mysteries one really h...        1
4  like period pieces clothing lingo enjoy myster...        1

In [6]:
df['reviewText']=df['reviewText'].astype(str)

In [8]:
df

                                               reviewText  overall
0       enjoy vintage books movies enjoyed reading boo...        1
1       book reissue old one author born 1910 era say ...        1
2       fairly interesting read old style terminology ...        1
3       never read amy brewster mysteries one really h...        1
4       like period pieces clothing lingo enjoy myster...        1
...                                                   ...      ...
982614  yasss hunny great read dre mess cherika refuse...        1
982615  enjoyed book beginning end far lex hoe sneaky ...        1
982616  great book cherika fool let man get away much ...        1
982617  say excellent book please believe definitely p...        1
982618  book everything hope alexus wise move lawd tho...        1

[982619 rows x 2 columns]

In [9]:
df['overall'].value_counts()

overall
1    925471
0     57148
Name: count, dtype: int64

In [10]:
df=df.head(10000)

In [11]:
# Train test split
from sklearn.model_selection import train_test_split

In [12]:
xtrain, xtest , ytrain , ytest = train_test_split(df['reviewText'], df['overall'] , test_size=0.25 , random_state=33)

In [13]:
xtrain

9126    let begin saying really enjoy eve vaughn books...
4952    amazing book kept wanting want put read jim ri...
5998    reason expound zane grey novels classic enjoya...
7066    aggie proves observant eye brains overcome agi...
9192    never even bothered give bad review one genera...
                              ...
57      like louis l amour books one exception want 6 ...
578     thank god free terrible 1 heroine meets hero 1...
5848    little book fun almost fell couch laughing int...
2439    lifelong christian raised christian home saved...
7188    since young growing grandmother nissa always d...
Name: reviewText, Length: 7500, dtype: object

In [14]:
# Perform bag of words
from sklearn.feature_extraction.text import CountVectorizer
bow= CountVectorizer()
xtrain_bow= bow.fit_transform(xtrain).toarray()
xtest_bow= bow.transform(xtest).toarray()

In [15]:
# Perform TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
xtrain_tfidf= tfidf.fit_transform(xtrain).toarray()
xtest_tfidf= tfidf.transform(xtest).toarray()

In [16]:
xtrain_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(xtrain_bow, ytrain)
nb_model_tfidf=GaussianNB().fit(xtrain_tfidf, ytrain)

In [18]:
from sklearn.metrics import confusion_matrix , accuracy_score, classification_report

In [19]:
y_pred_bow= nb_model_bow.predict(xtest_bow)

In [20]:
y_pred_tfidf= nb_model_tfidf.predict(xtest_tfidf)

In [21]:
print('BOW accuracy :', accuracy_score(ytest , y_pred_bow))

BOW accuracy : 0.738

In [23]:
confusion_matrix(ytest , y_pred_bow)

array([[  64,  184],
       [ 471, 1781]], dtype=int64)

In [22]:
print('TF-IDF accuracy :', accuracy_score(ytest , y_pred_tfidf))

TF-IDF accuracy : 0.7392

In [24]:
confusion_matrix(ytest , y_pred_tfidf)

array([[  64,  184],
       [ 468, 1784]], dtype=int64)