In [1]:
# !pip install gensim

In [2]:
import gensim
import pandas as pd

In [3]:
from gensim.models import KeyedVectors

# Load pre-trained Word2Vec model (takes some time, but no re-download)
wv = KeyedVectors.load_word2vec_format(
    "E:\MLnotebook\models\GoogleNews-vectors-negative300.bin",
    binary=True
)

In [4]:
messages= pd.read_csv('spam.csv', encoding='latin-1')

In [5]:
messages

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
messages.drop(columns={'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'}, axis=1, inplace=True)

In [7]:
messages

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
messages.rename(columns=({'v1': 'label', 'v2': 'message'}), inplace=True)

In [9]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()

In [11]:
import re
from nltk.corpus import stopwords

In [12]:
corpus= []
for i in range(0 , len(messages)):
    review= re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review= review.split()
    review= [ lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review= ' '.join(review)
    corpus.append(review)

In [13]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'going try month ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'back amp packing car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timing msg xuhui going learn nd may lesson',
 'oops let know roommate done',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decided anything tomo trying invite anything',
 'pls go ahead watt wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed lt gt inch',
 'call message missed call',
 'get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker',
 'thinked first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reached',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain killing',
 'ha ha ha good joke girl situation seeker',
 'part checking iq',
 'sorry roommate took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'k k performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still looking job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u getting yo need ticket one jacket done already used multis',
 'yes started send request make pain came back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml',
 'watching telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u ham',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks making birthday truly memorable',
 'aight hit get cash',
 'would ip address test considering computer minecraft server',
 'know grumpy old people mom like better lying always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'going dinner msg',
 'ok wif co like try new thing scared u dun like mah co u said loud',
 'gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla needed',
 'hmm uncle informed paying school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text way',
 'sir waiting mail',
 'swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class u',
 'freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k deleted contact',
 'sindu got job birla soft',
 'wine flowing nevering',
 'yup thk cine better co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one',
 'aaooooright work',
 'leaving house',
 'hello love get interview today happy good boy think missing',
 'customer service annoncement new year delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent trying contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discus liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlos make call',
 'u still going mall',
 'turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v like know satisfied experience reply toll free yes',
 'lifted hope offer money need especially end month approach hurt studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'going nothing great bye',
 'hello handsome finding job lazy working towards getting back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'got xmas radio time get',
 'jus reached home go bathe first si using net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry joined league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stay someone able give or every stool',
 'hope settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tired slept well past night',
 'easy ah sen got selected mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'o called ubandu run without installing hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'printed oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sound better',
 'although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched',
 'u remember old commercial',
 'late said website dont slipper',
 'asked call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly missed good night sleep',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect done get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'parked next mini coming today think',
 'yup',
 'anyway going shopping co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotic situation',
 'night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'sent type food like',
 'done handed celebration full swing yet',
 'got called tool',
 'wen u miss someone',
 'ok asked money far',
 'okie',
 'yeah think usual guy still passed last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friend call world ge',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u buy stuff',
 'themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend got money definitely buying end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost',
 'made day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friend afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message missed call',
 'hi da today class',
 'say good sign well know track record reading woman',
 'cool text parked',
 'reading text sent meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent wined dined',
 'sleeping surfing',
 'sorry call later',
 'u calling right call hand phone',
 'ok great thanx lot',
 'take post come must text happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnite tc practice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah help never iphone',
 'car hour half going apeshit',
 'today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay trying figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',
 'actor work work evening sleep late since unemployed moment always sleep late unemployed every day saturday',

In [14]:
from nltk import sent_tokenize, word_tokenize
from gensim.utils import simple_preprocess

In [15]:
words=[]
for sent in corpus:
    sent_token= sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [16]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
  'prize',
  'reward',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour'],
 ['mobile',
  'month',
  'entitled',
  'update',
  'latest',
  'colour',
  'mobile',
  'camera',
  'free',
  'call',
  'mobile',
  'update',
  'co',
  'free'],
 ['gonna',
  'home',
  'soon',
  'want',
  'talk',
  'stuff',
  'anymore',
  'tonight',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'win',
  'cash',
  'pound',
  'txt',
  'csh',
  'send',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'week',
  'free',
  'membership',
  'prize',
  'jackpot',
  'txt',
  'word',
  'claim',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['searching',
  'right',
  'word',
  'thank',
  'breather',
  'promise',
  'wont',
  'take',
  'help',
  'granted',
  'fulfil',
  'promise',
  'wonderful',
  'blessing',
  'time'],
 ['date', 'sunday'],
 ['use',
  'credit',
  'click',
  'wap',
  'link',
  'next',
  'txt',
  'message',
  'click',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching'],
 ['eh', 'remember', 'spell', 'name', 'yes', 'naughty', 'make', 'wet'],
 ['fine', 'way', 'feel', 'way', 'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'eg',
  'england',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['seriously', 'spell', 'name'],
 ['going', 'try', 'month', 'ha', 'ha', 'joking'],
 ['pay', 'first', 'lar', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'lunch',
  'go',
  'str',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff', 'alright', 'way', 'meet', 'sooner'],
 ['forced',
  'eat',
  'slice',
  'really',
  'hungry',
  'tho',
  'suck',
  'mark',
  'getting',
  'worried',
  'know',
  'sick',
  'turn',
  'pizza',
  'lol'],
 ['lol', 'always', 'convincing'],
 ['catch',
  'bus',
  'frying',
  'egg',
  'make',
  'tea',
  'eating',
  'mom',
  'left',
  'dinner',
  'feel',
  'love'],
 ['back', 'amp', 'packing', 'car', 'let', 'know', 'room'],
 ['ahhh', 'work', 'vaguely', 'remember', 'feel', 'like', 'lol'],
 ['wait', 'still', 'clear', 'sure', 'sarcastic', 'want', 'live'],
 ['yeah',
  'got',
  'apologetic',
  'fallen',
  'actin',
  'like',
  'spoilt',
  'child',
  'got',
  'caught',
  'till',
  'go',
  'badly',
  'cheer'],
 ['tell', 'anything'],
 ['fear', 'fainting', 'housework', 'quick', 'cuppa'],
 ['thanks',
  'subscription',
  'ringtone',
  'uk',
  'mobile',
  'charged',
  'month',
  'please',
  'confirm',
  'replying',
  'yes',
  'reply',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'timing',
  'msg',
  'xuhui',
  'going',
  'learn',
  'nd',
  'may',
  'lesson'],
 ['oops', 'let', 'know', 'roommate', 'done'],
 ['see', 'letter', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'saturday',
  'go',
  'texting',
  'see',
  'decided',
  'anything',
  'tomo',
  'trying',
  'invite',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'watt',
  'wanted',
  'sure',
  'great',
  'weekend',
  'abiola'],
 ['forget',
  'tell',
  'want',
  'need',
  'crave',
  'love',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'tried',
  'call',
  'reply',
  'sm',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'delivery',
  'tomorrow'],
 ['seeing'],
 ['great', 'hope', 'like', 'man', 'well', 'endowed', 'lt', 'gt', 'inch'],
 ['call', 'message', 'missed', 'call'],
 ['get', 'hep', 'immunisation', 'nigeria'],
 ['fair', 'enough', 'anything', 'going'],
 ['yeah', 'hopefully', 'tyler', 'could', 'maybe', 'ask', 'around', 'bit'],
 ['know',
  'stubborn',
  'even',
  'want',
  'go',
  'hospital',
  'kept',
  'telling',
  'mark',
  'weak',
  'sucker',
  'hospital',
  'weak',
  'sucker'],
 ['thinked', 'first', 'time', 'saw', 'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'smarter',
  'though',
  'get',
  'almost',
  'whole',
  'second',
  'gram',
  'lt',
  'gt'],
 ['fyi',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'crashing',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'embarassed',
  'accomodations',
  'thought',
  'liked',
  'since',
  'best',
  'could',
  'always',
  'seemed',
  'happy',
  'cave',
  'sorry',
  'give',
  'sorry',
  'offered',
  'sorry',
  'room',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'new',
  'jersey',
  'devil',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['know', 'mallika', 'sherawat', 'yesterday', 'find', 'lt', 'url', 'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'call',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'free',
  'bx',
  'ip',
  'pm',
  'dont',
  'miss'],
 ['sorry', 'call', 'later', 'meeting'],
 ['tell', 'reached'],
 ['yes', 'gauti', 'sehwag', 'odi', 'series'],
 ['gonna', 'pick', 'burger', 'way', 'home', 'even', 'move', 'pain', 'killing'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'situation', 'seeker'],
 ['part', 'checking', 'iq'],
 ['sorry', 'roommate', 'took', 'forever', 'ok', 'come'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'said',
  'wun',
  'cut',
  'short',
  'said',
  'cut',
  'look',
  'nice'],
 ['valued',
  'customer',
  'pleased',
  'advise',
  'following',
  'recent',
  'review',
  'mob',
  'awarded',
  'bonus',
  'prize',
  'call'],
 ['today',
  'song',
  'dedicated',
  'day',
  'song',
  'dedicate',
  'send',
  'ur',
  'valuable',
  'frnds',
  'first',
  'rply'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'claim',
  'txt',
  'dis',
  'morefrmmob',
  'aj'],
 ['hear', 'new', 'divorce', 'barbie', 'come', 'ken', 'stuff'],
 ['plane', 'give', 'month', 'end'],
 ['wah', 'lucky', 'man', 'save', 'money', 'hee'],
 ['finished', 'class'],
 ['hi', 'babe', 'im', 'home', 'wanna', 'something', 'xx'],
 ['performed'],
 ['call'],
 ['waiting', 'machan', 'call', 'free'],
 ['thats', 'cool', 'gentleman', 'treat', 'dignity', 'respect'],
 ['like', 'people', 'much', 'shy', 'pa'],
 ['operate', 'lt', 'gt'],
 ['still', 'looking', 'job', 'much', 'ta', 'earn'],
 ['sorry', 'call', 'later'],
 ['call', 'ah'],
 ['ok', 'way', 'home', 'hi', 'hi'],
 ['place', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'later', 'network', 'urgnt', 'sm'],
 ['real',
  'getting',
  'yo',
  'need',
  'ticket',
  'one',
  'jacket',
  'done',
  'already',
  'used',
  'multis'],
 ['yes',
  'started',
  'send',
  'request',
  'make',
  'pain',
  'came',
  'back',
  'back',
  'bed',
  'double',
  'coin',
  'factory',
  'gotta',
  'cash',
  'nitros'],
 ['really', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah', 'stand', 'close', 'tho', 'catch', 'something'],
 ['sorry',
  'pain',
  'ok',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'casualty',
  'mean',
  'done',
  'stuff',
  'moro',
  'includes',
  'time',
  'sheet',
  'sorry'],
 ['smile',
  'pleasure',
  'smile',
  'pain',
  'smile',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'see',
  'smiling'],
 ['please',
  'call',
  'customer',
  'service',
  'representative',
  'pm',
  'guaranteed',
  'cash',
  'prize'],
 ['havent',
  'planning',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'got',
  'show',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['free',
  'ringtone',
  'waiting',
  'collected',
  'simply',
  'text',
  'password',
  'mix',
  'verify',
  'get',
  'usher',
  'britney',
  'fml'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see', 'finish', 'load', 'loan', 'pay'],
 ['hi',
  'wk',
  'ok',
  'hols',
  'yes',
  'bit',
  'run',
  'forgot',
  'hairdresser',
  'appointment',
  'four',
  'need',
  'get',
  'home',
  'shower',
  'beforehand',
  'cause',
  'prob',
  'ham'],
 ['please', 'text', 'anymore', 'nothing', 'else', 'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'legal',
  'wen',
  'pick',
  'ave',
  'am',
  'xx'],
 ['still', 'looking', 'car', 'buy', 'gone', 'driving', 'test', 'yet'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['wow',
  'right',
  'mean',
  'guess',
  'gave',
  'boston',
  'men',
  'changed',
  'search',
  'location',
  'nyc',
  'something',
  'changed',
  'cuz',
  'signin',
  'page',
  'still',
  'say',
  'boston'],
 ['umma', 'life', 'vava', 'umma', 'love', 'lot', 'dear'],
 ['thanks',
  'lot',
  'wish',
  'birthday',
  'thanks',
  'making',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'hit', 'get', 'cash'],
 ['would',
  'ip',
  'address',
  'test',
  'considering',
  'computer',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'mom',
  'like',
  'better',
  'lying',
  'always',
  'one',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'busy'],
 ['plural', 'noun', 'research'],
 ['going', 'dinner', 'msg'],
 ['ok',
  'wif',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'loud'],
 ['gent',
  'trying',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'formal',
  'anyway',
  'fine',
  'juz',
  'tt',
  'eatin',
  'much',
  'puttin',
  'weight',
  'haha',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'cabin',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invited',
  'apartment',
  'went'],
 ['winner',
  'specially',
  'selected',
  'receive',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'tortilla',
  'needed'],
 ['hmm',
  'uncle',
  'informed',
  'paying',
  'school',
  'directly',
  'pls',
  'buy',
  'food'],
 ['private',
  'account',
  'statement',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'mobile',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'final',
  'try',
  'contact',
  'call',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['new', 'address', 'apple', 'pair', 'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'selected',
  'receive',
  'award',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['going', 'sao', 'mu', 'today', 'done'],
 ['predict', 'wat', 'time', 'finish', 'buying'],
 ['good', 'stuff'],
 ['know',
  'yetunde',
  'sent',
  'money',
  'yet',
  'sent',
  'text',
  'bother',
  'sending',
  'dont',
  'involve',
  'anything',
  'imposed',
  'anything',
  'first',
  'place',
  'apologise'],
 ['room'],
 ['hey',
  'girl',
  'hope',
  'well',
  'del',
  'bak',
  'long',
  'time',
  'give',
  'call',
  'sum',
  'time',
  'lucyxx'],
 ['much', 'cost'],
 ['home'],
 ['dear', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'know',
  'country',
  'algarve',
  'txt',
  'ansr',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'uk',
  'largest',
  'dogging',
  'network',
  'bt',
  'txting',
  'gravel',
  'nt',
  'ec',
  'msg'],
 ['haf', 'msn', 'yijue', 'hotmail', 'com'],
 ['call', 'meet'],
 ['check', 'room', 'befor', 'activity'],
 ['rcv',
  'msg',
  'chat',
  'svc',
  'free',
  'hardcore',
  'service',
  'text',
  'go',
  'get',
  'nothing',
  'must',
  'age',
  'verify',
  'yr',
  'network',
  'try'],
 ['got', 'lazy', 'type', 'forgot', 'lect', 'saw', 'pouch', 'like', 'nice'],
 ['text', 'way'],
 ['sir', 'waiting', 'mail'],
 ['swt',
  'thought',
  'nver',
  'get',
  'tired',
  'little',
  'thing',
  'lovable',
  'person',
  'coz',
  'somtimes',
  'little',
  'thing',
  'occupy',
  'biggest',
  'part',
  'heart',
  'gud',
  'ni'],
 ['know', 'pls', 'open', 'back'],
 ['yes', 'see', 'ya', 'dot'],
 ['whats', 'staff', 'name', 'taking', 'class'],
 ['freemsg',
  'replied',
  'text',
  'randy',
  'sexy',
  'female',
  'live',
  'local',
  'luv',
  'hear',
  'netcollex',
  'ltd',
  'per',
  'msg',
  'reply',
  'stop',
  'end'],
 ['ummma', 'call', 'check', 'life', 'begin', 'qatar', 'pls', 'pray', 'hard'],
 ['deleted', 'contact'],
 ['sindu', 'got', 'job', 'birla', 'soft'],
 ['wine', 'flowing', 'nevering'],
 ['yup', 'thk', 'cine', 'better', 'co', 'need', 'go', 'plaza', 'mah'],
 ['ok', 'ur', 'typical', 'reply'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['everywhere',
  'dirt',
  'floor',
  'window',
  'even',
  'shirt',
  'sometimes',
  'open',
  'mouth',
  'come',
  'flowing',
  'dream',
  'world',
  'without',
  'half',
  'chore',
  'time',
  'joy',
  'lot',
  'tv',
  'show',
  'see',
  'guess',
  'like',
  'thing',
  'must',
  'exist',
  'like',
  'rain',
  'hail',
  'mist',
  'time',
  'done',
  'become',
  'one'],
 ['aaooooright', 'work'],
 ['leaving', 'house'],
 ['hello',
  'love',
  'get',
  'interview',
  'today',
  'happy',
  'good',
  'boy',
  'think',
  'missing'],
 ['customer',
  'service',
  'annoncement',
  'new',
  'year',
  'delivery',
  'waiting',
  'please',
  'call',
  'arrange',
  'delivery'],
 ['winner',
  'specially',
  'selected',
  'receive',
  'cash',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'operator',
  'claim'],
 ['keep',
  'safe',
  'need',
  'miss',
  'already',
  'envy',
  'everyone',
  'see',
  'real',
  'life'],
 ['new', 'car', 'house', 'parent', 'new', 'job', 'hand'],
 ['love', 'excited', 'day', 'spend', 'make', 'happy'],
 ['pls',
  'stop',
  'bootydelious',
  'inviting',
  'friend',
  'reply',
  'yes',
  'see',
  'www',
  'sm',
  'ac',
  'bootydelious',
  'stop',
  'send',
  'stop',
  'frnd'],
 ['bangbabes',
  'ur',
  'order',
  'way',
  'receive',
  'service',
  'msg',
  'download',
  'ur',
  'content',
  'goto',
  'wap',
  'bangb',
  'tv',
  'ur',
  'mobile',
  'internet',
  'service',
  'menu'],
 ['place', 'ur', 'point', 'culture', 'module', 'already'],
 ['urgent',
  'trying',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr'],
 ['hi',
  'frnd',
  'best',
  'way',
  'avoid',
  'missunderstding',
  'wit',
  'beloved',
  'one'],
 ['great', 'escape', 'fancy', 'bridge', 'need', 'lager', 'see', 'tomo'],
 ['yes', 'completely', 'form', 'clark', 'also', 'utter', 'waste'],
 ['sir', 'need', 'axis', 'bank', 'account', 'bank', 'address'],
 ['hmmm',
  'thk',
  'sure',
  'got',
  'time',
  'hop',
  'ard',
  'ya',
  'go',
  'free',
  'abt',
  'muz',
  'call',
  'discus',
  'liao'],
 ['time', 'coming', 'later'],
 ['bloody',
  'hell',
  'cant',
  'believe',
  'forgot',
  'surname',
  'mr',
  'ill',
  'give',
  'clue',
  'spanish',
  'begin'],
 ['well', 'gonna', 'finish', 'bath', 'good', 'fine', 'night'],
 ['let', 'know', 'got', 'money', 'carlos', 'make', 'call'],
 ['still', 'going', 'mall'],
 ['turn',
  'friend',
  'staying',
  'whole',
  'show',
  'back',
  'til',
  'lt',
  'gt',
  'feel',
  'free',
  'go',
  'ahead',
  'smoke',
  'lt',
  'gt',
  'worth'],
 ['text', 'doesnt', 'reply', 'let', 'know', 'log'],
 ['hi',
  'spoke',
  'maneesha',
  'like',
  'know',
  'satisfied',
  'experience',
  'reply',
  'toll',
  'free',
  'yes'],
 ['lifted',
  'hope',
  'offer',
  'money',
  'need',
  'especially',
  'end',
  'month',
  'approach',
  'hurt',
  'studying',
  'anyways',
  'gr',
  'weekend'],
 ['lol', 'trust'],
 ['ok', 'gentleman', 'treat', 'dignity', 'respect'],
 ['guy', 'close'],
 ['going', 'nothing', 'great', 'bye'],
 ['hello',
  'handsome',
  'finding',
  'job',
  'lazy',
  'working',
  'towards',
  'getting',
  'back',
  'net',
  'mummy',
  'boytoy',
  'miss'],
 ['haha', 'awesome', 'minute'],
 ['please',
  'call',
  'customer',
  'service',
  'representative',
  'freephone',
  'pm',
  'guaranteed',
  'cash',
  'prize'],
 ['got', 'xmas', 'radio', 'time', 'get'],
 ['jus',
  'reached',
  'home',
  'go',
  'bathe',
  'first',
  'si',
  'using',
  'net',
  'tell',
  'finish'],
 ['unique',
  'enough',
  'find',
  'th',
  'august',
  'www',
  'areyouunique',
  'co',
  'uk'],
 ['sorry',
  'joined',
  'league',
  'people',
  'dont',
  'keep',
  'touch',
  'mean',
  'great',
  'deal',
  'friend',
  'time',
  'even',
  'great',
  'personal',
  'cost',
  'great',
  'week'],
 ['hi', 'finally', 'completed', 'course'],
 ['stop',
  'however',
  'suggest',
  'stay',
  'someone',
  'able',
  'give',
  'or',
  'every',
  'stool'],
 ['hope', 'settled', 'new', 'school', 'year', 'wishin', 'gr', 'day'],
 ['gud', 'mrng', 'dear', 'hav', 'nice', 'day'],
 ['got', 'person', 'story'],
 ['hamster', 'dead', 'hey', 'tmr', 'meet', 'pm', 'orchard', 'mrt'],
 ['hi',
  'kate',
  'evening',
  'hope',
  'see',
  'tomorrow',
  'bit',
  'bloody',
  'babyjontet',
  'txt',
  'back',
  'xxx'],
 ['found', 'enc', 'lt', 'gt'],
 ['sent', 'lt', 'gt', 'buck'],
 ['hello',
  'darlin',
  'ive',
  'finished',
  'college',
  'txt',
  'finish',
  'love',
  'kate',
  'xxx'],
 ['account',
  'refilled',
  'successfully',
  'inr',
  'lt',
  'decimal',
  'gt',
  'keralacircle',
  'prepaid',
  'account',
  'balance',
  'lt',
  'decimal',
  'gt',
  'transaction',
  'id',
  'kr',
  'lt',
  'gt'],
 ['goodmorning', 'sleeping', 'ga'],
 ['call', 'alter', 'ok'],
 ['say',
  'like',
  'dat',
  'dun',
  'buy',
  'ericsson',
  'oso',
  'cannot',
  'oredi',
  'lar'],
 ['entered',
  'cabin',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invited',
  'apartment',
  'went'],
 ['aight', 'yo', 'dat', 'straight', 'dogg'],
 ['please',
  'give',
  'connection',
  'today',
  'lt',
  'decimal',
  'gt',
  'refund',
  'bill'],
 ['shoot', 'big', 'load', 'get', 'ready'],
 ['bruv', 'hope', 'great', 'break', 'rewarding', 'semester'],
 ['home', 'always', 'chat'],
 ['good', 'study', 'well'],
 ['yup', 'noe', 'leh'],
 ['sound', 'great', 'home'],
 ['finally', 'match', 'heading', 'towards', 'draw', 'prediction'],
 ['tired', 'slept', 'well', 'past', 'night'],
 ['easy', 'ah', 'sen', 'got', 'selected', 'mean', 'good'],
 ['take', 'exam', 'march'],
 ['yeah',
  'think',
  'use',
  'gt',
  'atm',
  'register',
  'sure',
  'anyway',
  'help',
  'let',
  'know',
  'sure',
  'ready'],
 ['ok', 'prob', 'take', 'ur', 'time'],
 ['called',
  'ubandu',
  'run',
  'without',
  'installing',
  'hard',
  'disk',
  'use',
  'copy',
  'important',
  'file',
  'system',
  'give',
  'repair',

In [17]:
# Creating the model from scratch
model=gensim.models.Word2Vec(words)

In [18]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'text',
 'love',
 'want',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'going',
 'home',
 'stop',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'pls',
 'please',
 'co',
 'msg',
 'min',
 'make',
 'dear',
 'night',
 'message',
 'say',
 'well',
 'thing',
 'much',
 'great',
 'claim',
 'oh',
 'hope',
 'hey',
 'number',
 'friend',
 'happy',
 'wat',
 'work',
 'give',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'cash',
 'yeah',
 'really',
 'amp',
 'life',
 'meet',
 'im',
 'babe',
 'find',
 'morning',
 'service',
 'thanks',
 'miss',
 'year',
 'last',
 'uk',
 'com',
 'would',
 'nokia',
 'anything',
 'lol',
 'also',
 'care',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'urgent',
 'contact',
 'something',
 'buy',
 'wait',
 'cant',
 'first',
 'place',
 'help',
 'went',
 'someone',
 'box',
 'nice',
 'even',
 'next',
 'guy',
 'wish',
 'tonight',
 'word',
 'around',
 'show',
 'soon',
 'could',
 'money',
 'customer',
 'sleep',
 'chat',
 'many',
 'late',
 'per',
 'gonna',
 'ya',
 'sm',
 'leave',
 'name',
 'wan',
 'always',
 'lot',
 'dun',
 'gud',
 'pm',
 'st',
 'end',
 'told',
 'waiting',
 'hello',
 'fine',
 'month',
 'girl',
 'hour',
 'heart',
 'special',
 'haha',
 'coming',
 'minute',
 'people',
 'person',
 'yet',
 'getting',
 'guaranteed',
 'may',
 'thk',
 'th',
 'smile',
 'done',
 'ppm',
 'best',
 'use',
 'thought',
 'try',
 'god',
 'offer',
 'stuff',
 'holiday',
 'talk',
 'class',
 'mean',
 'live',
 'car',
 'lunch',
 'line',
 'cost',
 'man',
 'finish',
 'job',
 'start',
 'draw',
 'problem',
 'bit',
 'plan',
 'trying',
 'thats',
 'house',
 'yup',
 'hr',
 'never',
 'meeting',
 'better',
 'account',
 'pobox',
 'long',
 'cool',
 'rate',
 'ill',
 'ready',
 'dat',
 'chance',
 'weekend',
 'game',
 'mind',
 'half',
 'world',
 'real',
 'latest',
 'enjoy',
 'wk',
 'yo',
 'play',
 'guess',
 'room',
 'check',
 'sir',
 'pic',
 'camera',
 'wanna',
 'eat',
 'voucher',
 'nothing',
 'awarded',
 'look',
 'lar',
 'receive',
 'boy',
 'shit',
 'sweet',
 'another',
 'big',
 'liao',
 'dinner',
 'po',
 'ah',
 'bt',
 'birthday',
 'landline',
 'might',
 'quite',
 'age',
 'luv',
 'kiss',
 'ever',
 'video',
 'jus',
 'question',
 'xxx',
 'watch',
 'land',
 'watching',
 'bed',
 'probably',
 'called',
 'tv',
 'early',
 'pa',
 'baby',
 'point',
 'orange',
 'nd',
 'thanx',
 'aight',
 'worry',
 'speak',
 'fun',
 'den',
 'forgot',
 'nite',
 'actually',
 'sat',
 'maybe',
 'shall',
 'apply',
 'ringtone',
 'wont',
 'two',
 'remember',
 'hear',
 'bus',
 'princess',
 'network',
 'bad',
 'part',
 'reach',
 'code',
 'easy',
 'dream',
 'dunno',
 'office',
 'left',
 'pay',
 'shopping',
 'evening',
 'face',
 'hurt',
 'put',
 'award',
 'wife',
 'little',
 'fuck',
 'didnt',
 'dis',
 'dad',
 'leh',
 'mail',
 'movie',
 'true',
 'school',
 'working',
 'enough',
 'mate',
 'sound',
 'xx',
 'anyway',
 'selected',
 'yr',
 'made',
 'looking',
 'thank',
 'gift',
 'afternoon',
 'everything',
 'collect',
 'tmr',
 'pound',
 'without',
 'entry',
 'missing',
 'town',
 'asked',
 'detail',
 'valid',
 'sexy',
 'join',
 'okay',
 'must',
 'came',
 'price',
 'wif',
 'though',
 'since',
 'xmas',
 'hav',
 'update',
 'mob',
 'wanted',
 'answer',
 'missed',
 'wot',
 'lesson',
 'til',
 'important',
 'pain',
 'collection',
 'wake',
 'able',
 'run',
 'book',
 'bring',
 'abt',
 'plus',
 'decimal',
 'colour',
 'plz',
 'away',
 'charge',
 'juz',
 'stay',
 'change',
 'test',
 'de',
 'date',
 'alright',
 'wen',
 'saw',
 'attempt',
 'till',
 'music',
 'yesterday',
 'double',
 'hair',
 'havent',
 'dude',
 'else',
 'weekly',
 'shop',
 'friendship',
 'making',
 'top',
 'optout',
 'id',
 'drink',
 'net',
 'trip',
 'food',
 'credit',
 'bored',
 'oso',
 'lei',
 'online',
 'haf',
 'goin',
 'family',
 'feeling',
 'address',
 'gr',
 'player',
 'coz',
 'ard',
 'either',
 'national',
 'sch',
 'club',
 'delivery',
 'hot',
 'driving',
 'tried',
 'bonus',
 'wid',
 'smoke',
 'post',
 'lose',
 'sad',
 'si',
 'http',
 'mom',
 'sae',
 'story',
 'beautiful',
 'together',
 'order',
 'head',
 'full',
 'brother',
 'nt',
 'busy',
 'ring',
 'believe',
 'calling',
 'tot',
 'second',
 'drive',
 'smiling',
 'leaving',
 'close',
 'chikku',
 'info',
 'await',
 'sleeping',
 'happen',
 'huh',
 'old',
 'poly',
 'set',
 'walk',
 'noe',
 'eve',
 'row',
 'mum',
 'saying',
 'awesome',
 'simple',
 'started',
 'match',
 'drop',
 'hand',
 'private',
 'finished',
 'thinking',
 'congrats',
 'cause',
 'tomo',
 'hl',
 'okie',
 'aft',
 'parent',
 'suite',
 'pub',
 'news',
 'took',
 'rite',
 'email',
 'mths',
 'company',
 'angry',
 'caller',
 'wil',
 'reason',
 'auction',
 'break',
 'unsubscribe',
 'tc',
 'content',
 'gd',
 'neva',
 'taking',
 'statement',
 'tho',
 'sister',
 'forget',
 'card',
 'valentine',
 'everyone',
 'available',
 'mine',
 'final',
 'touch',
 'whats',
 'anyone',
 'alone',
 'sun',
 'gal',
 'fancy',
 'opt',
 'search',
 'loving',
 'knw',
 'carlos',
 'bank',
 'lucky',
 'worth',
 'type',
 'choose',
 'whatever',
 'dating',
 'treat',
 'expires',
 'found',
 'ticket',
 'open',
 'winner',
 'hit',
 'frnd',
 'smth',
 'decided',
 'friday',
 'song',
 'welcome',
 'ltd',
 'kind',
 'boytoy',
 'anytime',
 'college',
 'saturday',
 'fast',
 'identifier',
 'gbp',
 'secret',
 'gone',
 'hard',
 'party',
 'visit',
 'exam',
 'sub',
 'prob',
 'mobileupd',
 'happened',
 'far',
 'uncle',
 'congratulation',
 'ha',
 'quiz',
 'hows',
 'pretty',
 'outside',
 'mu',
 'fucking',
 'goodmorning',
 'used',
 'chennai',
 'lovely',
 'wonderful',
 'oredi',
 'darlin',
 'project',
 'fri',
 'sea',
 'bout',
 'least',
 'wrong',
 'tel',
 'wonder',
 'term',
 'light',
 'wit',
 'camcorder',
 'drug',
 'nope',
 'operator',
 'finally',
 'read',
 'crazy',
 'freemsg',
 'wkly',
 'seeing',
 'whole',
 'telling',
 'ni',
 'jay',
 'frnds',
 'log',
 'ten',
 'support',
 'hmm',
 'sunday',
 'unlimited',
 'savamob',
 'cum',
 'meant',
 'listen',
 'earlier',
 'case',
 'cd',
 'fone',
 'hungry',
 'blue',
 'mrng',
 'hold',
 'frm',
 'snow',
 'course',
 'wq',
 'fr',
 'motorola',
 'bslvyl',
 'un',
 'die',
 'within',
 'hmmm',
 'talking',
 'pas',
 'store',
 'paper',
 'area',
 'txts',
 'happiness',
 'mah',
 'ago',
 'child',
 'sex',
 'invited',
 'single',
 'currently',
 'yar',
 'felt',
 'stupid',
 'moment',
 'mayb',
 'download',
 'joy',
 'balance',
 'press',
 'india',
 'film',
 'reading',
 'luck',
 'christmas',
 'eh',
 'cut',
 'move',
 'tired',
 'enter',
 'sk',
 'side',
 'john',
 'almost',
 'as',
 'rock',
 'lost',
 'march',
 'dnt',
 'etc',
 'understand',
 'park',
 'couple',
 'father',
 'hee',
 'gas',
 'valued',
 'mr',
 'na',
 'computer',
 'via',
 'return',
 'reveal',
 'laptop',
 'swing',
 'semester',
 'bill',
 'figure',
 'promise',
 'ugh',
 'picking',
 'load',
 'eye',
 'sell',
 'an',
 'xy',
 'darren',
 'nyt',
 'kid',
 'askd',
 'gym',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'extra',
 'gotta',
 'sort',
 'knew',
 'charged',
 'confirm',
 'comp',
 'hospital',
 'difficult',
 'wow',
 'ac',
 'red',
 'correct',
 'grin',
 'surprise',
 'information',
 'complimentary',
 'heard',
 'photo',
 'sending',
 'shower',
 'rental',
 'ish',
 'met',
 'supposed',
 'direct',
 'seen',
 'asap',
 'rply',
 'muz',
 'orchard',
 'reward',
 'save',
 'truth',
 'slow',
 'whenever',
 'checking',
 'wine',
 'lover',
 'loan',
 'small',
 'wana',
 'lovable',
 'idea',
 'leaf',
 'laugh',
 'discount',
 'kate',
 'joke',
 'page',
 'cheer',
 'police',
 'study',
 'abiola',
 'std',
 'crave',
 'gn',
 'slowly',
 'usf',
 'loved',
 'ex',
 'fact',
 'fantasy',
 'comin',
 'hg',
 'safe',
 'bcoz',
 'road',
 'request',
 'hmv',
 'dogging',
 'link',
 'monday',
 'member',
 'wap',
 'eg',
 'blood',
 'asking',
 'rent',
 'clean',
 'txting',
 'somebody',
 'door',
 'rest',
 'train',
 'remove',
 'bath',
 'entered',
 'woke',
 'nobody',
 'rd',
 'reached',
 'callertune',
 'hoping',
 'england',
 'short',
 'energy',
 'situation',
 'kick',
 'doctor',
 'teach',
 'copy',
 'admirer',
 'somewhere',
 'ldn',
 'less',
 'doin',
 'spend',
 'empty',
 'normal',
 'oops',
 'med',
 'del',
 'different',
 'hw',
 'nah',
 'ringtones',
 'water',
 'catch',
 'rakhesh',
 'opinion',
 'cover',
 'write',
 'custcare',
 'bb',
 'across',
 'convey',
 'representative',
 'gettin',
 'bag',
 'wc',
 'getzed',
 'tonite',
 'pray',
 'deal',
 'summer',
 'wishing',
 'yep',
 'voice',
 'glad',
 'worried',
 'ge',
 'fantastic',
 'merry',
 'gap',
 'bathe',
 'gave',
 'pete',
 'men',
 'usual',
 'em',
 'ho',
 'deep',
 'la',
 'booked',
 'sale',
 'sony',
 'cheap',
 'ntt',
 'warm',
 'il',
 'turn',
 'otherwise',
 'mm',
 'poor',
 'cr',
 'mistake',
 'immediately',
 'sick',
 'staying',
 'ip',
 'decide',
 'lect',
 'lazy',
 'sunshine',
 'studying',
 'dead',
 'buying',
 'using',
 'bos',
 'especially',
 'forever',
 'rain',
 'completely',
 'specially',
 'doesnt',
 'mrt',
 'password',
 'ending',
 'ice',
 'flight',
 'ive',
 'stand',
 'bx',
 'trust',
 'urself',
 'none',
 'rcvd',
 'access',
 'gay',
 'silent',
 'cake',
 'user',
 'tampa',
 'fall',
 'al',
 'sport',
 'excuse',
 'hotel',
 'rose',
 'thinkin',
 'unless',
 'sitting',
 'charity',
 'seriously',
 'near',
 'excellent',
 'comuk',
 'meh',
 'logo',
 'mode',
 'wondering',
 'others',
 'brings',
 'digital',
 'reference',
 'tht',
 'bluetooth',
 'reaching',
 'kinda',
 'result',
 'hiya',
 'style',
 'moral',
 'weed',
 'round',
 'flag',
 'accept',
 'possible',
 'sofa',
 'bold',
 'starting',
 'seems',
 'pc',
 'forwarded',
 'street',
 'add',
 'goodnight',
 'noon',
 'ldew',
 'indian',
 'mon',
 'colleague',
 'bid',
 'cup',
 'norm',
 'disturb',
 'self',
 'awaiting',
 'longer',
 'thru',
 'inc',
 'din',
 'trouble',
 'mark',
 'moon',
 'tuesday',
 'black',
 'student',
 'library',
 'cancel',
 'cute',
 'giving',
 'complete',
 'ave',
 'umma',
 'workin',
 'funny',
 ...]

In [19]:
model.corpus_count

5564

In [20]:
model.epochs

5

In [21]:
model.wv.similar_by_word('bad')

[('go', 0.9991636276245117),
 ('miss', 0.9991616606712341),
 ('find', 0.9991248846054077),
 ('da', 0.9991058111190796),
 ('one', 0.9991052746772766),
 ('buy', 0.9990995526313782),
 ('play', 0.9990965127944946),
 ('gud', 0.9990904927253723),
 ('friend', 0.9990900754928589),
 ('already', 0.9990856647491455)]

In [22]:
model.wv['good'].shape

(100,)

In [23]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [24]:
import numpy as np

In [25]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key])

In [26]:
# !pip install tqdm

In [27]:
from tqdm import tqdm

In [28]:
# Apply word2vec on entire sentences
x=[]
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

  0%|          | 0/5564 [00:00<?, ?it/s]C:\Users\sawan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\sawan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5564/5564 [00:00<00:00, 13911.08it/s]

In [29]:
x

[0.0030193606,
 0.0022757854,
 0.0037018002,
 0.0038171147,
 0.0035660935,
 0.00383759,
 0.0036480292,
 0.0025233082,
 0.0042499052,
 0.0046612374,
 0.004015951,
 0.0048430823,
 0.0053257844,
 0.0030061326,
 0.0025208085,
 0.0031189956,
 0.003909072,
 0.002646856,
 0.0042683138,
 0.0033041248,
 0.0029907697,
 0.0033933143,
 0.0029123742,
 0.0031200512,
 0.0038246727,
 0.0024442535,
 0.0041242284,
 0.0023751736,
 0.0052690753,
 0.004202242,
 0.005295654,
 0.0042520124,
 0.0046618436,
 0.00010373908,
 0.0034087372,
 0.0035976064,
 0.0034157666,
 0.0036508043,
 0.002889173,
 0.0028533423,
 0.0033525229,
 0.004196897,
 0.0047779903,
 0.0007561513,
 0.005173725,
 0.0055135433,
 0.00412955,
 0.003861579,
 0.003079479,
 0.0030166705,
 0.0037288738,
 0.0048674005,
 0.0024196934,
 0.003121427,
 0.0033303567,
 0.006832678,
 0.00335755,
 0.0038866552,
 0.0031989256,
 0.004739499,
 0.0042242487,
 0.0029334072,
 0.0017370853,
 0.0027500167,
 0.0030128341,
 0.0032915191,
 0.004085661,
 0.0044678426,
 0.004238799,
 0.003872809,
 0.0025940978,
 0.001607901,
 0.004442117,
 nan,
 0.007623136,
 0.0056595565,
 0.001952148,
 0.0047707097,
 0.008872257,
 0.003764911,
 0.004548354,
 0.0045903395,
 0.0043419963,
 0.004022199,
 0.0046240315,
 0.003701943,
 0.0036244502,
 0.0040355506,
 0.004637726,
 0.003945025,
 0.0024242364,
 0.0033522742,
 0.0034641228,
 0.005565367,
 0.0038335896,
 0.003775947,
 0.0029088503,
 0.0026423873,
 0.0032233838,
 0.0034026841,
 0.003474722,
 0.0032583564,
 0.0025233082,
 0.0022011243,
 0.0033578924,
 0.0040930426,
 0.0045309635,
 0.0024873405,
 0.004112897,
 0.003340566,
 nan,
 0.0044596856,
 0.004358563,
 0.00504302,
 0.0025652105,
 0.0027699505,
 0.003211919,
 0.002460714,
 0.0023570687,
 0.0041898405,
 0.004714114,
 0.0032918642,
 0.0035238278,
 0.004561331,
 0.002749124,
 0.005168798,
 0.004189473,
 0.0019693936,
 0.0042028874,
 0.005495518,
 0.0055750995,
 0.006348457,
 0.0033371095,
 0.0032561168,
 0.0034129892,
 0.0025966298,
 0.006016221,
 0.002619434,
 0.004691811,
 0.0033788187,
 0.005733513,
 0.0025262905,
 0.003319127,
 0.00553608,
 0.0044212635,
 0.0023776996,
 0.0035899694,
 0.003572055,
 0.0055993185,
 0.0053343303,
 0.00072594435,
 0.0036164247,
 0.005626173,
 0.0025233082,
 0.003643874,
 0.0051732147,
 0.0022452136,
 0.0044488763,
 0.004109872,
 0.0033027844,
 0.004078972,
 0.0032993245,
 0.0039966386,
 0.00476491,
 0.0040298747,
 0.0051274253,
 0.0051002665,
 0.0037362925,
 0.0037181315,
 0.003018663,
 0.0029278651,
 0.0033090382,
 0.0039343406,
 0.002588761,
 0.004110527,
 0.005767359,
 0.005896755,
 0.004710994,
 0.0048197294,
 0.0044944016,
 0.0034981575,
 0.00206098,
 0.0018981814,
 0.0042767213,
 0.0033541655,
 0.0031609267,
 0.0028699716,
 0.0050778836,
 0.0052540004,
 0.0031576566,
 0.0054402393,
 0.0038484144,
 0.0021204373,
 0.003798244,
 0.0040474683,
 0.0041963286,
 0.004302838,
 0.0030600114,
 0.0039974055,
 0.006707872,
 0.0059880484,
 0.002479085,
 0.0058260905,
 0.0014866474,
 0.005531252,
 0.0032314125,
 0.0027699505,
 0.0022218607,
 0.004886965,
 0.0035024667,
 0.0026660091,
 0.0048738304,
 0.00406561,
 0.0025839508,
 0.003789599,
 0.0026329511,
 0.00296033,
 0.0034164123,
 0.0028386605,
 0.0046835644,
 0.0046563763,
 0.0025372896,
 0.004548354,
 0.00278856,
 0.0041941223,
 0.004623186,
 0.0040440834,
 0.0043555964,
 0.0034577819,
 0.0048096706,
 0.0041391053,
 0.005163986,
 0.0021275785,
 0.0039000197,
 0.0039305105,
 0.007030375,
 0.0035091487,
 0.0024141157,
 0.004078706,
 0.004239978,
 0.0018737933,
 0.0022308617,
 0.002072044,
 0.0037933711,
 0.0019915707,
 0.0037786046,
 0.004443016,
 0.0019768686,
 0.0035533388,
 0.004146348,
 0.002956048,
 0.0031148284,
 0.0049781916,
 0.0039045257,
 0.004666308,
 0.0047394307,
 0.0037890002,
 0.0040004356,
 0.005062173,
 0.0038187075,
 0.003262235,
 0.0042097187,
 0.0043066205,
 0.003056,
 0.0021259643,
 0.004457824,
 0.0042067883,
 0.0016895082,
 0.0038735145,
 0.0029681353,
 0.0034562375,
 0.0037067044,
 0.0039009198,
 0.002155946,
 0.002235072,
 0.0061255223,
 0.0032361913,
 0.0034859437,
 0.0021086417,
 0.0046850666,
 0.0042677387,
 0.003121427,
 0.0007682357,
 0.0043968083,
 0.003747078,
 0.0034393677,
 0.0039285515,
 0.0043880027,
 0.0029707348,
 0.0041927635,
 0.0025775437,
 0.0034241097,
 0.0056261276,
 0.0051228227,
 0.0044083116,
 0.0029138997,
 0.0035295472,
 0.0056623477,
 0.0033677153,
 0.003949285,
 0.0036178895,
 0.0038497793,
 nan,
 0.0031893863,
 0.0035582478,
 0.0035461886,
 0.003482952,
 0.0033808716,
 -0.00024162671,
 0.0028526061,
 0.0048300605,
 0.004557389,
 0.004223107,
 0.0046723173,
 0.0016032744,
 0.0025094268,
 0.0046618353,
 0.004253583,
 0.0014886117,
 0.002697348,
 0.0038137678,
 0.0040778425,
 0.003771594,
 0.004227584,
 0.0055135433,
 0.004416634,
 0.0031893777,
 0.004392515,
 0.003146709,
 0.004810636,
 0.0031808359,
 0.0037922964,
 0.003852814,
 0.0038648623,
 0.0041577923,
 0.0038182656,
 0.0015118874,
 0.004548354,
 0.0042420495,
 0.0033320028,
 0.0042402693,
 nan,
 0.00386106,
 0.0029703102,
 0.004859017,
 0.0026785643,
 0.0039390638,
 0.0034983042,
 0.0035225525,
 0.0037561227,
 0.004265142,
 0.0031871663,
 0.0029479258,
 0.0046280255,
 0.0024194894,
 0.004146348,
 0.0039610965,
 0.0038594326,
 0.0038585986,
 0.0024802336,
 0.00289076,
 0.004432215,
 0.0026644275,
 0.003841445,
 0.005192501,
 0.0036308193,
 0.005267792,
 0.0050236736,
 0.0037135791,
 0.0030707847,
 0.0044251387,
 0.006009267,
 0.0044428706,
 0.0032665022,
 0.0026291665,
 0.0033134755,
 0.0040668533,
 0.0037523073,
 0.0035530778,
 0.0033332002,
 0.003378911,
 0.0044041756,
 0.003935647,
 0.003489677,
 0.0011546556,
 0.0056526787,
 0.0035149222,
 0.0038492077,
 0.0032560157,
 0.0018477999,
 0.0032956859,
 0.003507235,
 0.0040157977,
 0.0037049938,
 0.0040780217,
 0.0041845995,
 0.002995977,
 0.0029300868,
 0.003696537,
 0.004729532,
 0.0032692733,
 0.0023283383,
 0.003215671,
 0.004227411,
 0.0036768236,
 0.0039475346,
 0.00414561,
 0.0014452613,
 0.0035357913,
 0.003151065,
 0.006470443,
 0.0030199145,
 0.0041392683,
 0.0032098421,
 0.0052248556,
 0.0024550676,
 0.0050233235,
 0.0036508678,
 0.0035314027,
 0.004923454,
 0.0039800587,
 0.00043559575,
 0.0054869214,
 0.0049545034,
 0.003471442,
 0.002060993,
 0.0034413259,
 0.004191101,
 0.0037742716,
 0.0039469944,
 0.0028799078,
 0.0039147264,
 0.0009570054,
 0.0057562846,
 0.006081845,
 0.0041060755,
 0.0037358014,
 0.00460768,
 0.0035425066,
 0.0037125477,
 0.004093806,
 0.001856196,
 0.004548354,
 0.0055569545,
 0.0032472059,
 0.0030194637,
 0.004406749,
 0.0032546981,
 0.004303919,
 nan,
 0.00583865,
 0.0027322858,
 0.0037398988,
 0.0048726746,
 0.003692185,
 0.003893102,
 0.0024736281,
 0.0040972466,
 0.0024835991,
 0.0037416439,
 0.004127573,
 0.004104166,
 0.0034853427,
 0.0044505782,
 0.0042320318,
 0.003720254,
 0.0028671727,
 0.0039007966,
 0.003989275,
 0.0034611663,
 0.0025189042,
 0.0043113995,
 0.003192482,
 0.0039802883,
 0.003408618,
 0.0031287407,
 0.0028925624,
 0.0035584175,
 0.0041864156,
 0.0024537817,
 0.0030826398,
 0.003404294,
 0.0036569475,
 0.001010061,
 0.004805649,
 0.004408547,
 0.0018350322,
 0.00363721,
 0.004161727,
 0.0041304263,
 0.00335755,
 0.003886655,
 0.0066899094,
 0.006900389,
 0.0039092917,
 0.0029852684,
 0.0031145625,
 0.0024149914,
 0.0031864028,
 0.003482914,
 0.005917915,
 0.0032694726,
 0.002753226,
 0.004684951,
 0.003732256,
 0.002002672,
 0.00426776,
 nan,
 0.002805283,
 0.0051599517,
 0.0021677131,
 0.0033605343,
 0.0013431426,
 0.003786291,
 -0.00045562707,
 0.0041020834,
 0.003698516,
 0.0044619064,
 0.0030201138,
 0.0026132646,
 0.0051642195,
 0.0057323836,
 0.00088691415,
 0.004953546,
 0.0019506662,
 0.004244825,
 0.002950676,
 0.003746782,
 0.0023945172,
 0.0037578314,
 0.004136965,
 0.004859017,
 0.0036547969,
 0.004165424,
 0.003598696,
 0.004512787,
 0.00288646,
 0.0037428162,
 0.0039563873,
 0.00513772,
 0.0020870725,
 0.0031430256,
 0.0011104345,
 0.0033788737,
 0.004655204,
 0.0046570334,
 0.0024191234,
 0.0070645274,
 0.0036827312,
 0.0026820654,
 0.0034024387,
 0.00491405,
 0.004128384,
 0.0015182366,
 0.004515388,
 0.0020771127,
 0.005417736,
 0.0027368949,
 0.0035158093,
 0.0035691531,
 0.0035945692,
 0.002625283,
 0.00504302,
 0.004588056,
 0.0031251234,
 0.0027698441,
 0.0042055915,
 0.0028485004,
 0.0027834345,
 0.0026694918,
 0.005824628,
 0.0012637943,
 0.005400514,
 0.0014753412,
 0.007469069,
 0.0050194985,
 0.0025825659,
 0.005353175,
 0.0036324854,
 0.0014288182,
 0.0038356052,
 0.004961941,
 0.0037244407,
 0.0037630915,
 0.0045519113,
 0.002578203,
 0.0018216899,
 0.0024647801,
 0.0041625625,
 0.0040747705,
 0.0037047009,
 0.0037578314,
 0.0053605633,
 0.003438307,
 0.0037941227,
 0.004207032,
 0.0039759562,
 0.0034298666,
 0.0030798216,
 0.0016381246,
 0.0037203121,
 0.005270901,
 0.003226576,
 0.00302007,
 0.005703536,
 0.0024519924,
 0.003933801,
 0.0025909503,
 0.004383755,
 0.0035512564,
 0.0042193704,
 0.0037629423,
 0.0044258484,
 0.0029389493,
 0.0035908439,
 0.0040986813,
 0.0021015801,
 0.004213698,
 0.0027388427,
 0.005283983,
 0.0046040155,
 0.0038762651,
 0.003972532,
 0.0028075692,
 0.0035621019,
 0.0042311223,
 0.0030213634,
 0.0045353943,
 0.0038929717,
 0.004402316,
 0.0027434314,
 0.004717354,
 0.004253604,
 0.0048857485,
 0.0019507188,
 0.0039009755,
 0.0038347794,
 0.0012779125,
 0.0024154545,
 0.0043099998,
 0.003773928,
 0.00268895,
 0.0023238678,
 0.0036566427,
 0.003571934,
 0.00350202,
 0.0037578314,
 0.0030735214,
 0.006657594,
 0.0016757472,
 0.0030142434,
 0.0036661103,
 0.004239322,
 0.004302838,
 0.0037725787,
 0.004300353,
 0.004022199,
 0.004052222,
 0.0064067906,
 0.001708344,
 0.0024050402,
 0.0036102808,
 0.00345946,
 0.0021976293,
 0.0024356986,
 0.0044353744,
 0.0057819877,
 0.0030107086,
 0.004831465,
 0.0020314937,
 0.0029139118,
 0.0047617643,
 0.0039768685,
 0.0066572,
 0.003145086,
 0.004036028,
 0.0031534678,
 0.0026811194,
 0.0044167964,
 0.0033953679,
 0.0028478373,
 0.0033723528,
 0.003848609,
 0.0030218437,
 0.003290132,
 0.003448627,
 0.0041189655,
 0.0026806158,
 0.0042792195,
 0.002094264,
 0.0025604009,
 0.0031416884,
 0.0044479654,
 0.003185867,
 0.005665041,
 0.0034963572,
 0.0030201138,
 0.0036839505,
 0.005389438,
 0.00287235,
 0.004548354,
 0.0022846712,
 0.0030788532,
 0.0029841876,
 0.0035859486,
 0.0014356598,
 0.0022723458,
 0.004085757,
 0.0038492077,
 0.0021360405,
 0.003894828,
 0.00521043,
 0.0044120234,
 0.004366818,
 0.0039404877,
 0.0037458814,
 0.0052771745,
 0.0057783443,
 0.0035125215,
 0.004667966,
 0.0026531518,
 0.0013579306,
 0.0037994764,
 0.003462917,
 0.0039471877,
 0.0042748223,
 0.002496724,
 0.000762856,
 0.0030871376,
 0.0032463453,
 0.0021323927,
 0.0037789019,
 0.0035976227,
 0.0029096052,
 0.0037296363,
 0.003887344,
 0.003984225,
 0.0056487136,
 0.0035914101,
 0.0027510617,
 0.0044242456,
 0.003794115,
 0.0031446875,
 0.0022111847,
 0.0041702366,
 0.0041753044,
 0.0052120904,
 0.0036823682,
 0.0037917686,
 0.002454373,
 0.0038855213,
 0.0048125116,
 0.003655691,
 0.0038881938,
 0.0024062877,
 0.0029501251,
 0.0036984908,
 0.0013670736,
 0.0045923083,
 0.0037408588,
 0.003779526,
 0.005362936,
 0.0039836946,
 0.002478532,
 0.0036493225,
 0.0030661938,
 0.004548354,
 0.0056623477,
 0.0030661025,
 0.0026003467,
 0.0027068364,
 0.0037112006,
 0.005110868,
 0.0015118874,
 0.003833888,
 0.004586952,
 0.0031950695,
 0.0040960982,
 0.0035415324,
 0.002805283,
 0.0031200305,
 nan,
 0.0039759562,
 0.0040310025,
 0.003184711,
 0.003632155,
 0.0038740276,
 0.004612746,
 0.0041963286,
 0.0039179265,
 0.0037988923,
 0.0026753964,
 0.0017424633,
 0.0035229516,
 0.0050749285,
 0.004327887,
 0.0050970423,
 0.0038862913,
 0.0058658384,
 0.0041070003,
 0.0044646473,
 0.0049729394,
 0.0053072823,
 nan,
 nan,
 0.005252862,
 0.0034362888,
 0.0040885364,
 0.0034139033,
 0.008872257,
 0.0032490033,
 0.0039945175,
 0.0037315467,
 0.0030902587,
 0.0023835183,
 0.0034411156,
 0.0046674297,
 nan,
 0.0037455678,
 0.0029660075,
 0.004249602,
 0.0031114018,
 0.0034220105,
 0.0030107086,
 0.0020698109,
 0.004323152,
 0.0051569757,
 0.0038073969,
 0.003284206,
 0.003644666,
 0.003446506,
 0.0048878933,
 0.0037737668,
 0.002661109,
 0.0052145533,
 0.0045668106,
 0.0035510587,
 0.0037316626,
 0.004153779,
 0.0029760364,
 0.004817862,
 0.0031712013,
 0.0041606207,
 0.0064329477,
 0.0036378384,
 0.0020946898,
 0.003331329,
 0.0029199915,
 0.004244825,
 0.0034730094,
 0.0037097367,
 0.002299881,
 0.003472189,
 0.003116105,
 0.004224959,
 0.005815603,
 0.004508763,
 0.0015082784,
 0.0025710363,
 0.005750332,
 0.0017961183,
 0.0033457156,
 0.0038921665,
 0.0012386509,
 0.0040821517,
 0.0029048077,
 0.0037578314,
 0.0029082492,
 0.004835502,
 0.0049327305,
 0.003998013,
 0.0038670236,
 0.0049702786,
 0.004971496,
 0.0038562538,
 0.005342714,
 0.0033375623,
 0.004239978,
 0.004239978,
 0.00248597,
 0.0040028505,
 0.003936008,
 0.003235534,
 0.0028661082,
 -0.00012327317,
 0.0040462,
 0.0027398407,
 nan,
 0.0025265904,
 0.0030193627,
 0.0026858493,
 nan,
 0.003194201,
 0.0046250834,
 0.0042057186,
 0.0044046594,
 0.0026204258,
 0.0041363067,
 0.003775947,
 0.0036396189,
 0.0015240678,
 0.0034611516,
 0.0016807312,
 0.0029703649,
 0.0048135724,
 0.0028296718,
 0.0031344716,
 0.0015094625,
 0.0037216803,
 0.003635197,
 0.0026690818,
 0.0033699812,
 0.0031727517,
 0.005825807,
 0.003842802,
 0.004285989,
 0.003592304,
 0.0026849657,
 0.0032964807,
 0.0038701044,
 0.0056441263,
 0.0023749855,
 0.004119407,
 0.0025348538,
 0.0052062464,
 0.0025596584,
 0.0023043267,
 0.0039781784,
 0.004799697,
 0.0038747424,
 0.0026158977,
 0.0038065922,
 0.004153014,
 0.0038451303,
 0.0030443603,
 0.001903179,
 0.0006973483,
 0.0038020832,
 0.0030104108,
 0.003078984,
 0.0029118585,
 0.0035468324,
 0.00301922,
 0.00370981,
 0.004262746,
 0.0046214466,
 0.0038902436,
 0.0070195366,
 0.0062922905,
 0.0029130373,
 0.0034241423,
 0.0033294908,
 0.0038304382,
 0.0032620176,
 0.0038201255,
 0.0034198388,
 nan,
 0.0031705615,
 0.0043894663,
 0.005437112,
 0.003571934,
 0.002974569,
 0.0056261276,
 0.0047660163,
 0.0032962454,
 0.0049823606,
 0.0027950222,
 0.0025513424,
 0.0033214977,
 0.003127875,
 0.0033452057,
 0.0056051505,
 0.0036739723,
 0.0029062864,
 0.0026744013,
 0.00438851,
 0.004905711,
 0.0036119276,
 0.003803223,
 0.0039133923,
 0.0028146275,
 0.0036878383,
 0.0025025476,
 0.005087255,
 0.0065158526,
 0.003592572,
 0.004116696,
 0.002903808,
 0.0036907375,
 0.0048296903,
 0.004173813,
 0.0028298674,
 0.005816307,
 0.0045376588,
 0.0036129688,
 0.0024986784,
 0.0042697852,
 0.0032621121,
 0.0016252124,
 0.0050778836,
 ...]

In [30]:
len(x)

5564

In [31]:
# Independent feature
x_new= np.array(x)

In [32]:
x_new.shape

(5564,)

In [33]:
x_new[0]

0.0030193605925887823